
[general]
  live_config_reload = false

[window]
  startup_mode = "Windowed" 
  opacity = 0.9


[font]
  normal = { family = "monospace", style = "Regular" }
  size = 22

[colors.primary]
 ## foreground = "#DC9916"  ### light orange color
  foreground = "#BD8B28"  ### dark orange color
