[general]
  live_config_reload = false

[window]
  opacity = 0.9

[scrolling]
  history = 5000

[font]
  normal = { family = "AdwaitaMono", style = "Regular" }
  size = 22

[colors.primary]
  foreground = "#B57D01"   ##   Orange
# foreground = "#BD8B28"  ### dark orange color
