#!/bin/bash

  rm ~/.bashrc
  wget https://github.com/icysilviu/linux/raw/main/.bashrc
  source .bashrc
  
  wget https://github.com/icysilviu/linux/raw/main/.vimrc

  cd .config
  mkdir hypr waybar alacritty gtk-3.0
  cd alacritty
     wget https://github.com/icysilviu/linux/raw/main/alacritty.toml
     cd ..
  cd hypr
     wget https://github.com/icysilviu/linux/raw/main/hyprland.conf
     wget https://github.com/icysilviu/linux/raw/main/hyprpaper.conf
     cd ..
  cd waybar
     wget https://github.com/icysilviu/linux/raw/main/config.jsonc
     wget https://github.com/icysilviu/linux/raw/main/style.css
     cd ..
  cd gtk-3.0
     wget https://github.com/icysilviu/linux/raw/main/settings.ini
     cd ..
