#preload = /home/ice/Pictures/bussines-lady.jpg
#wallpaper = Virtual-1, /home/ice/Pictures/bussines-lady.jpg

wallpaper {
    monitor = Virtual-1
    path = /home/ice/Pictures/bussines-lady.jpg
    fit_mode = cover
}


